{type:"class",attributes:{"name":"AssertionError","packageName":"qx.core","superClass":"qx.type.BaseError","fullName":"qx.core.AssertionError","type":"class"},children:[{type:"desc",attributes:{"text":"<p>Assertion errors are thrown if an assertion in {@link qx.core.Assertion}\nfails.</p>"}},{type:"constructor",children:[{type:"method",attributes:{"overriddenFrom":"qx.type.BaseError","isCtor":"true","name":"ctor"},children:[{type:"params",children:[{type:"param",attributes:{"name":"comment"},children:[{type:"desc",attributes:{"text":"<p>Comment passed to the assertion call</p>"}},{type:"types",children:[{type:"entry",attributes:{"type":"String"}}]}]},{type:"param",attributes:{"name":"failMessage"},children:[{type:"desc",attributes:{"text":"<p>Fail message provided by the assertion</p>"}},{type:"types",children:[{type:"entry",attributes:{"type":"String"}}]}]}]}]}]},{type:"methods",children:[{type:"method",attributes:{"name":"getStackTrace"},children:[{type:"desc",attributes:{"text":"<p>Stack trace of the error</p>"}},{type:"return",children:[{type:"desc",attributes:{"text":"<p>The stack trace of the location the exception was thrown</p>"}},{type:"types",children:[{type:"entry",attributes:{"type":"String","dimensions":"1"}}]}]}]}]}]}